### ISSUE TITLE
Cannot use numpy uint64 for map size.

### ISSUE THREAD

**Issue by kwohlfahrt** [inducer/pyopencl#155]
The following code doesn't work.

```
#!/usr/bin/env python3
import pyopencl as cl
import numpy as np

ctx = cl.create_some_context()
cq = cl.CommandQueue(ctx)

# counter_dt = np.dtype('uint32') # Works
counter_dt = np.dtype('uint64') # Doesn't work
data_dt = np.dtype('float32')

sizes = np.array([24], dtype=counter_dt)

buf = cl.Buffer(ctx, cl.mem_flags.READ_WRITE, sizes[0] * data_dt.itemsize)
(buf_map, _) = cl.enqueue_map_buffer(
    cq, buf, cl.map_flags.READ, 0, (sizes[0],), data_dt, is_blocking=True,
)
```

The error is:

```
Traceback (most recent call last):
  File "map.py", line 14, in <module>
    buf = cl.Buffer(ctx, cl.mem_flags.READ_WRITE, sizes[0] * data_dt.itemsize)
  File "/usr/lib/python3/dist-packages/pyopencl/cffi_cl.py", line 1065, in __init__
    ptr_buffer, context.ptr, flags, size, c_hostbuf))
TypeError: an integer is required
```

If the `counter_dt` line is switched for `uint32`, it works.

**Comment by inducer** [comment]
I can reproduce your issue, but I don't believe it's related to PyOpenCL. I think it's a numpy issue:

```
>>> np.uint64(24) * 15
360.0
```

I.e. `uint64 * int` seems to come out to a float (?!), and that's what PyOpenCL (IMO rightfully) gets grumpy about.

**Comment by inducer** [comment]
`int64 * int` seems OK, FWIW.

**Comment by inducer** [comment]
I'll close this for now. If you believe it's a PyOpenCL problem after all, feel free to reopen.
