### ISSUE TITLE
pyopencl may break programs using multiprocessing

### ISSUE THREAD

**Issue by aomader** [inducer/pyopencl#156]
I have a rather involved program that makes heavy use of `multiprocessing`'s process `Pool`. However, it gets weird when I simply create a `pyopencl.Context` by calling `pyopencl.create_some_context()` at the top of my script, without changing anything. After that addition, the program hangs for no obvious reason when it tries to join a `Pool` after all workitems are done, see stacktrace below created by aborting the program.

This happens not with the first `Pool` instance, but rather with a later one. And this is simply caused by calling `pyopencl.create_some_context()` before running the actual code.

```pybt
Traceback (most recent call last):
  File "test.py", line 45, in <module>
    scores = model.test(test_image.image_data)
  File "/home/oli/Projects/rfl/rfl/__init__.py", line 215, in test
    print('added')
  File "/usr/lib64/python3.5/multiprocessing/pool.py", line 575, in __exit__
    self.terminate()
  File "/usr/lib64/python3.5/multiprocessing/pool.py", line 505, in terminate
    self._terminate()
  File "/usr/lib64/python3.5/multiprocessing/util.py", line 186, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/usr/lib64/python3.5/multiprocessing/pool.py", line 569, in _terminate_pool
    p.join()
  File "/usr/lib64/python3.5/multiprocessing/process.py", line 121, in join
    res = self._popen.wait(timeout)
  File "/usr/lib64/python3.5/multiprocessing/popen_fork.py", line 51, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/usr/lib64/python3.5/multiprocessing/popen_fork.py", line 29, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
```

**Edit:** I just used a different `PYOPENCL_CTX` (previously I used my Intel CPU now I'm using my Intel GPU using Beignet) and now everything runs. Thus it might be related to the OpenCL runtime of the Intel device?

**Comment by inducer** [comment]
i don't think this is really a limitation of PyOpenCL. `fork()`, the basic mechanism behind creation of processes on Linux, is not really a safe operation once a GPU context has been created. Sharing thread pools across `fork()` is also not really safe, which is what the CPU runtime might attempt. Sending PyOpenCL objects (contexts, queues, etc) back and forth via pickles (as `multiprocessing` does) also doesn't make lots of sense. Overall, I'd say the only safe way to use `multiprocessing` with PyOpenCL is to create a pool of workers and spin up a new PyOpenCL context within each worker.

I'll close this. If you disagree with my point of view, feel free to comment or reopen.
