### ISSUE TITLE
Error calling "import pyopencl as cl" on Python 3.6 but fine on Python 2.7

### ISSUE THREAD

**Issue by dendisuhubdy** [inducer/pyopencl#202]
```
(dev3) suhubdyd@bart16:~/research/frameworks/pyopencl/examples$ python benchmark.py 
Traceback (most recent call last):
  File "benchmark.py", line 5, in <module>
    import pyopencl as cl
  File "/u/suhubdyd/.conda/envs/dev3/lib/python3.6/site-packages/pyopencl-2017.2-py3.6-linux-x86_64.egg/pyopencl/__init__.py", line 37, in <module>
    import pyopencl.cffi_cl as _cl
  File "/u/suhubdyd/.conda/envs/dev3/lib/python3.6/site-packages/pyopencl-2017.2-py3.6-linux-x86_64.egg/pyopencl/cffi_cl.py", line 39, in <module>
    from pyopencl._cffi import ffi as _ffi
ImportError: /u/suhubdyd/.conda/envs/dev3/lib/python3.6/site-packages/pyopencl-2017.2-py3.6-linux-x86_64.egg/pyopencl/_cffi.abi3.so: undefined symbol: clSVMFree
```

**Comment by inducer** [comment]
This issue tracker is for bugs, not technical support. Please send a message to the mailing list for tech support.
