### ISSUE TITLE
Creating a second context fails with clCreateContext failed: INVALID_DEVICE

### ISSUE THREAD

**Issue by robbert-harms** [inducer/pyopencl#223]
An user of my PyOpenCL dependent software package (https://github.com/cbclab/MDT/issues/5) reported an issue with context creation, which we could eventually trace to an issue within PyOpenCL.

In short, the following statements:
```
import pyopencl as cl

platform = cl.get_platforms()[0]
device = platform.get_devices()[0]
context = cl.Context([device])

platform = cl.get_platforms()[0]
device = platform.get_devices()[0]
context = cl.Context([device])
```
crashes with:
```
$ python3
Python 3.6.1 (default, Apr 27 2017, 10:57:56)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyopencl as cl
>>>
>>> platform = cl.get_platforms()[0]
>>> device = platform.get_devices()[0]
>>> context = cl.Context([device])
>>>
>>> platform = cl.get_platforms()[0]
>>> device = platform.get_devices()[0]
>>> context = cl.Context([device])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/share/software/user/open/py-mdt/0.10.8_py36/lib/python3.6/site-packages/pyopencl/cffi_cl.py", line 811, in __init__
    num_devices, _devices))
  File "/share/software/user/open/py-mdt/0.10.8_py36/lib/python3.6/site-packages/pyopencl/cffi_cl.py", line 664, in _handle_error
    raise e
pyopencl.cffi_cl.LogicError: clCreateContext failed: INVALID_DEVICE
```

System specifications:
```
$ nvidia-smi -L
GPU 0: Tesla P100-SXM2-16GB (UUID: GPU-[...])
```

```
$ python3 benchmark.py
Execution time of test without OpenCL:  0.10260295867919922 s
===============================================================
Platform name: NVIDIA CUDA
Platform profile: FULL_PROFILE
Platform vendor: NVIDIA Corporation
Platform version: OpenCL 1.2 CUDA 9.1.84
---------------------------------------------------------------
Device name: Tesla P100-SXM2-16GB
Device type: GPU
Device memory:  16280 MB
Device max clock speed: 1480 MHz
Device compute units: 56
Device max work group size: 1024
Device max work item sizes: [1024, 1024, 64]
Data points: 8388608
Workers: 256
Preferred work group size multiple: 32
Execution time of test: 0.000208416 s
Results OK
```

Any idea to what this might be?

Thank you in advance,

Robbert

**Comment by robbert-harms** [comment]
Btw, deleting the context in between seems to work:
```
import pyopencl as cl

platform = cl.get_platforms()[0]
device = platform.get_devices()[0]
context = cl.Context([device])

del context

platform = cl.get_platforms()[0]
device = platform.get_devices()[0]
context = cl.Context([device])
```

no crash.

**Comment by inducer** [comment]
If they have the (Nvidia I'm guessing) compute device set to "exclusive" (or some such, I forget the terminology) mode (using `nvidia-smi`), then it would only allow creation of a single context.

**Comment by robbert-harms** [comment]
Hello Andreas,

That indeed did solve the issue. Thanks for the head-ups!

Best,

Robbert
