### ISSUE TITLE
Kernel.get_work_group_info raises AttributeError

### ISSUE THREAD

**Issue by t20100** [inducer/pyopencl#244]
On Debian 9, with python 3.5.3 and pyopencl 2018.2, I get an error when calling `Kernel.get_work_group_info`: 
`AttributeError: 'pyopencl._cl.Kernel' object has no attribute '_wg_info_cache'`

To reproduce:
```
>>> import pyopencl as cl
>>> ctx = cl.create_some_context()
[...]
>>> queue = cl.CommandQueue(ctx)
>>> prg = cl.Program(ctx, """
... __kernel void sum(
...     __global const float *a_g, __global const float *b_g, __global float *res_g)
... {
...   int gid = get_global_id(0);
...   res_g[gid] = a_g[gid] + b_g[gid];
... }
... """).build()
>>> kernel = prg.all_kernels()[0]
>>> kernel.get_work_group_info(cl.kernel_work_group_info.WORK_GROUP_SIZE, prg.devices[0])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mntdirect/_scisoft/users/tvincent/venv/py3ocl-test/lib/python3.5/site-packages/pyopencl/__init__.py", line 818, in kernel_get_work_group_info
    return self._wg_info_cache[param, device]
AttributeError: 'pyopencl._cl.Kernel' object has no attribute '_wg_info_cache'
```

Defining the missing attribute makes it work:
```
>>> kernel._wg_info_cache = {}
>>> kernel.get_work_group_info(cl.kernel_work_group_info.WORK_GROUP_SIZE, prg.devices[0])
1024
```

It seems the monkey patch `kernel_init` for `Kernel.__init__` in `pyopencl/__init__.py` does not get called.

**Comment by inducer** [comment]
https://gitlab.tiker.net/inducer/pyopencl/merge_requests/54

**Comment by inducer** [comment]
Should be fixed. Thanks for the report!

**Comment by t20100** [comment]
No more issue with the tip of the master. Thanks!
