### ISSUE TITLE
Program fails to build on macOS mojave

### ISSUE THREAD

**Issue by YVin3D** [inducer/pyopencl#252]
So I'm trying to run pyopencl on macOS mojave and for some reason I keep getting a `clBuildProgram failed: BUILD_PROGRAM_FAILURE` error.

My code is pretty basic, but it won't compile:

```
import numpy as np
import pyopencl as cl
from pyopencl.clrandom import rand as clrand

context = cl.create_some_context()
queue = cl.CommandQueue(context)
clrand(queue, (50,), np.float32)
```

Whenever I run the above code I get the following error:

```

> Traceback (most recent call last):
>   File "/Users/Joe/Desktop/CIS 497/Code/pyopenclTest.py", line 8, in <module>
>     clrand(queue, (50,), np.float32)
>   File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyopencl/clrandom.py", line 755, in rand
>     gen.fill_uniform(result, a=a, b=b))
>   File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyopencl/clrandom.py", line 665, in fill_uniform
>     scale=(b-a), shift=a, queue=queue)
>   File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyopencl/clrandom.py", line 642, in _fill
>     self.get_gen_kernel(ary.dtype, distribution)
>   File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pytools/__init__.py", line 598, in wrapper
>     result = function(obj, *args, **kwargs)
>   File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyopencl/clrandom.py", line 623, in get_gen_kernel
>     prg = cl.Program(self.context, src).build()
>   File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyopencl/__init__.py", line 510, in build
>     options_bytes=options_bytes, source=self._source)
>   File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyopencl/__init__.py", line 554, in _build_and_catch_errors
>     raise err
> pyopencl._cl.RuntimeError: clBuildProgram failed: BUILD_PROGRAM_FAILURE - clBuildProgram failed: BUILD_PROGRAM_FAILURE - clBuildProgram failed: BUILD_PROGRAM_FAILURE
> 
> Build on <pyopencl.Device 'Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz' on 'Apple' at 0xffffffff>:

```

Is this a bug with mojave?

**Comment by inducer** [comment]
Did you truncate the error message? Were their further lines after the "Build on" line?

**Comment by YVin3D** [comment]
Yes, I didn't think it was relevant but here are the lines:

```
(options: -I /usr/local/lib/python3.6/site-packages/pyopencl/cl)

(source saved as /var/folders/db/bszlwnr57k14302m81bsqllw0000gn/T/tmps_3_231x.cl)
```

**Comment by inducer** [comment]
It appears as though this might be a CPU driver bug on Apple. Prior versions of Apple's CL drivers accepted this code, as do all other ICDs of which I'm aware. To do OpenCL work on CPUs on Apple, i recommend you use pocl. See PyOpenCL's install instructions on how to install it.

**Comment by YVin3D** [comment]
Yeah that fixed it for me. Thanks!
