### ISSUE TITLE
python gl_interop_demo.py 

### ISSUE THREAD

**Issue by ghost** [inducer/pyopencl#258]
```
(cl) ~/work/pyopencl/examples$ python gl_interop_demo.py 
Traceback (most recent call last):
  File "gl_interop_demo.py", line 74, in <module>
    glutInit(sys.argv)
  File "/home/ubuntu/anaconda3/envs/cl/lib/python3.6/site-packages/OpenGL/GLUT/special.py", line 333, in glutInit
    _base_glutInit( ctypes.byref(count), holder )
  File "/home/ubuntu/anaconda3/envs/cl/lib/python3.6/site-packages/OpenGL/platform/baseplatform.py", line 407, in __call__
    self.__name__, self.__name__,
OpenGL.error.NullFunctionError: Attempt to call an undefined function glutInit, check for bool(glutInit) before calling
(cl) ~/work/pyopencl/examples$ cd ..

```

```

(cl) ~/work/pyopencl$ python
Python 3.6.6 | packaged by conda-forge | (default, Oct 12 2018, 14:08:43) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 


```

**Comment by inducer** [comment]
This issue tracker is for bugs, not technical support. Please send a message to the mailing list for tech support. One reason for this request is that I am typically the only one who sees issue email, and I am unable to handle the tech support load on my own.
