### ISSUE TITLE
Docs: pyopencl.array.arange() arguments ambiguous

### ISSUE THREAD

**Issue by luziferius** [inducer/pyopencl#274]
I tried to use array.arange() function and failed to get it to work for quite some (looking at help(), opening the online docs…).
This is the full documentation for [`pyopencl.array.arange`](https://documen.tician.de/pyopencl/array.html#pyopencl.array.arange). The same is given using help() on the interactive prompt:

```
pyopencl.array.arange(queue, *args, **kwargs)
    Create a Array filled with numbers spaced step apart, starting from start and ending at stop.
    For floating point arguments, the length of the result is ceil((stop - start)/step).
    This rule may result in the last element of the result being greater than stop.
    dtype, if not specified, is taken as the largest common type of start, stop and step.
    Changed in version 2011.1: context argument was deprecated.
    Changed in version 2011.2: allocator keyword argument was added.
```
This is not really helpful to determine the actual signature.
The first sentence implies the arguments are supplied as (step, start, stop). Three lines below, it is (start, stop, step).

I’d suggest to:
- Specify that the dtype is a required keywords argument
- Replace the rather ambiguous `*args`, as it is not really helpful. Maybe change the shown signature to something like:  `arange(queue, [start, ] stop [, step], **kwargs`)
- Say that start defaults to 0, step defaults to 1. It were nice, if one does not have to read the source code or do experiments.

```python3
>>> pyopencl.array.arange(queue, 0, 10)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/Daten/Projekte/bzip2cl/trunk/virtEnv/lib/python3.6/site-packages/pyopencl/array.py", line 2087, in arange
    raise TypeError("arange requires a dtype argument")
TypeError: arange requires a dtype argument
arange requires a dtype argument

# Now wtih step. The docs say the dtype is optional:
# 'dtype, if not specified, is taken as the largest common type of start, stop and step.'
>>> pyopencl.array.arange(queue, 0, 10, 1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/Daten/Projekte/bzip2cl/trunk/virtEnv/lib/python3.6/site-packages/pyopencl/array.py", line 2087, in arange
    raise TypeError("arange requires a dtype argument")
TypeError: arange requires a dtype argument
arange requires a dtype argument

# Ok, let’s try adding the dtype, the given signature and text don’t indicate how it should be added:
>>> pyopencl.array.arange(queue, 0, 10, np.uint8)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/Daten/Projekte/bzip2cl/trunk/virtEnv/lib/python3.6/site-packages/pyopencl/array.py", line 2082, in arange
    step = dtype.type(inf.step)
ValueError: invalid __array_struct__
invalid __array_struct__
# Also adding the step:
>>> pyopencl.array.arange(queue, 0, 10, 2, np.uint8)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/Daten/Projekte/bzip2cl/trunk/virtEnv/lib/python3.6/site-packages/pyopencl/array.py", line 2057, in arange
    raise ValueError("too many arguments")
ValueError: too many arguments
too many arguments

# It works, if the dtype is specified using a keyword argument.
>>> pyopencl.array.arange(queue, 10, dtype=np.uint8)
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)
```

**Comment by inducer** [comment]
I agree. How's this? https://gitlab.tiker.net/inducer/pyopencl/merge_requests/76

**Comment by luziferius** [comment]
Looks good. This gives all information needed.

Thank you very much for providing and maintaining this awesome project!

**Comment by inducer** [comment]
Thanks for taking a look, and for the suggestion.
