### ISSUE TITLE
Password length exceeds the input buffer

### ISSUE THREAD

**Issue by henshin** [inducer/pyopencl#294]
I was trying this module with a large wordlist such as rockyou.txt and it seems it can't handle long passwords.
This is the error I'm getting:

```
Traceback (most recent call last):
  File ".\md5test.py", line 95, in <module>
    main(sys.argv)
  File ".\md5test.py", line 89, in main
    md5_test(opencl_algos,passwordlist)
  File ".\md5test.py", line 43, in md5_test
    clresult=opencl_algo.cl_md5(ctx,passwordlist)
  File "C:\tests\opencl_brute-master\Library\opencl.py", line 471, in cl_md5
    return self.concat(self.opencl_ctx.run(bufStructs, func, iter(passwordlist), b"", self.mdPadLenFunc))
  File "C:\tests\opencl_brute-master\Library\opencl.py", line 435, in concat
    return [obj for l in ll for obj in l]
  File "C:\tests\opencl_brute-master\Library\opencl.py", line 435, in <listcomp>
    return [obj for l in ll for obj in l]
  File "C:\tests\opencl_brute-master\Library\opencl.py", line 180, in run
    "password #" + str(i) + ", '" + pw.decode() + "' (length " + str(pwLen) + ") exceeds the input buffer (length " + str(inBufSize_bytes) + ") when padded"
AssertionError: password #1020, 'lllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll' (length 165) exceeds the input buffer (length 128) when padded
```
Didn't look too much into the code but maybe just doubling the buffer sizes could solve it.

**Comment by inducer** [comment]
You've come to the wrong place. This is likely a problem with the `opencl_brute` program/module you're using, not with PyOpenCL. PyOpenCL knows nothing about passwords FWIW.

**Comment by henshin** [comment]
Many apologies, you're right. I was in a rush before leaving the house and posted the issue on your project by mistake.
