### ISSUE TITLE
A `Program` object becomes unusable after querying its attribute

### ISSUE THREAD

**Issue by fjarri** [inducer/pyopencl#322]
MacOS 10.15.2, Python 3.7.5, PyOpenCL 2019.1.2

Code:
```
import pyopencl as cl

ctx = cl.create_some_context()
queue = cl.CommandQueue(ctx)

prg = cl.Program(ctx, """
__kernel void sum(
    __global const float *a_g, __global const float *b_g, __global float *res_g)
{
  int gid = get_global_id(0);
  res_g[gid] = a_g[gid] + b_g[gid];
}
""")
print(prg.devices)

prg = prg.build()
```

This fails on the last line, for any chosen device, with an error:
```
/Users/bogdan/.pyenv/versions/3.7.5/lib/python3.7/site-packages/pyopencl/__init__.py:1289: UserWarning: Pre-build attribute access defeats compiler caching.
  return info_method(self, info_attr)
[<pyopencl.Device 'AMD Radeon Pro Vega 20 Compute Engine' on 'Apple' at 0x1021d00>]
Traceback (most recent call last):
  File "/Users/bogdan/.pyenv/versions/3.7.5/lib/python3.7/site-packages/pyopencl/__init__.py", line 436, in __getattr__
    knl = Kernel(self, attr)
  File "/Users/bogdan/.pyenv/versions/3.7.5/lib/python3.7/site-packages/pyopencl/__init__.py", line 771, in kernel_init
    kernel_old_init(self, prg, name)
pyopencl._cl.LogicError: clCreateKernel failed: INVALID_PROGRAM_EXECUTABLE

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "t2.py", line 16, in <module>
    prg = prg.build()
  File "/Users/bogdan/.pyenv/versions/3.7.5/lib/python3.7/site-packages/pyopencl/__init__.py", line 476, in build
    self._context, options)
  File "/Users/bogdan/.pyenv/versions/3.7.5/lib/python3.7/site-packages/pyopencl/__init__.py", line 451, in __getattr__
    "info attribute or as a kernel name" % attr)
AttributeError: '_context' was not found as a program info attribute or as a kernel name
```

If one removes the `print(prg.devices)`, everything works normally.

**Comment by inducer** [comment]
https://gitlab.tiker.net/inducer/pyopencl/merge_requests/103

**Comment by fjarri** [comment]
Thank you!
