### ISSUE TITLE
ImportError in Windows

### ISSUE THREAD

**Issue by ma-sadeghi** [inducer/pyopencl#442]
```python
>>> import pyopencl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Amin\anaconda3\envs\test\lib\site-packages\pyopencl\__init__.py", line 28, in <module>
    import pyopencl.cltypes  # noqa: F401
  File "C:\Users\Amin\anaconda3\envs\test\lib\site-packages\pyopencl\cltypes.py", line 22, in <module>
    from pyopencl.tools import get_or_register_dtype
  File "C:\Users\Amin\anaconda3\envs\test\lib\site-packages\pyopencl\tools.py", line 37, in <module>
    from pyopencl._cl import bitlog2  # noqa: F401
ImportError: DLL load failed while importing _cl: The specified procedure could not be found.
```

**Comment by isuruf** [comment]
Do you have a `OpenCL.dll` somewhere in `C:\System32`?

**Comment by ma-sadeghi** [comment]
@isuruf Yes, I just checked.

**Comment by isuruf** [comment]
That's probably interfering here. Moving that `OpenCL.dll` would fix this issue, but might break some other software.

**Comment by ma-sadeghi** [comment]
That's right, I renamed the file and everything worked just fine. Any idea why do I have `OpenCL.dll` in the first place? Does it get installed automatically when I install NVIDIA drivers?
