### ISSUE TITLE
Difference in behavior between PYOPENCL_CTX and PYOPENCL_TEST

### ISSUE THREAD

**Issue by matthiasdiener** [inducer/pyopencl#781]
**Describe the bug**
Parsing of `PYOPENCL_CTX` and `PYOPENCL_TEST` is implemented differently, leading to a different selection behavior. An example is given below. #780 is another example.

**To Reproduce**

```console
$ clinfo -l
Platform #0: AMD Accelerated Parallel Processing
 `-- Device #0: gfx90a:sramecc+:xnack-

$ PYOPENCL_TEST=AMD:90 python -c "import pyopencl; pyopencl.choose_devices()"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/p/lustre1/diener3/Work/enew/pyopencl/pyopencl/__init__.py", line 1561, in choose_devices
    for _plat, devs in get_test_platforms_and_devices():
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/p/lustre1/diener3/Work/enew/pyopencl/pyopencl/tools.py", line 646, in get_test_platforms_and_devices
    [find_cl_obj(devs, dev_id)
  File "/p/lustre1/diener3/Work/enew/pyopencl/pyopencl/tools.py", line 646, in <listcomp>
    [find_cl_obj(devs, dev_id)
     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/p/lustre1/diener3/Work/enew/pyopencl/pyopencl/tools.py", line 618, in find_cl_obj
    return objs[num]
           ~~~~^^^^^
IndexError: list index out of range

$ PYOPENCL_CTX=AMD:90 python -c "import pyopencl; pyopencl.choose_devices()"
$ # works fine
```

**Expected behavior**
Having the same selection logic may be beneficial.

**Environment (please complete the following information):**
 - OS: [e.g. Linux] Any
 - ICD Loader and version: [e.g. ocl-icd 2.3.1] ocl-icd 2.3.2
 - ICD and version: [e.g. pocl 1.8] Any
 - CPU/GPU: [e.g. Nvidia Titan V] Any
  - Python version: [e.g. 3.10] 3.11
  - PyOpenCL version: [e.g. 2021.1] 2024.2.7

**Additional context**

**Comment by alexfikl** [comment]
The issue seems to be that the access to that `objs` array isn't guarded here:
https://github.com/inducer/pyopencl/blob/846fede414c0db8dc8e738719cbf5eba30cf9594/pyopencl/tools.py#L618
and the integer "90" in the "AMD:90" string matches that branch. The same-ish code in "choose_devices" is nicely guarded:
https://github.com/inducer/pyopencl/blob/846fede414c0db8dc8e738719cbf5eba30cf9594/pyopencl/__init__.py#L1640-L1641
Would probably be nice to unify that parsing :grin:
